language: php

php:
    - 5.5
    - 5.4
    - 5.3

services:
    - mysql

before_script:
    # install behat, mink etc
    # Have to prefer source or hit github rate limit
    - composer install --no-interaction --prefer-source
    # db setup
    - mysql -e 'create database terminaslt;'
    - mv web/database.config.travis web/database.config.php

    - sudo apt-get install apache2
    - sudo a2enmod actions
    - sudo a2enmod rewrite
    - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
    - sudo sed -i -e "/DocumentRoot/i\ServerName knpu_qa.l" /etc/apache2/sites-available/default
    - echo "127.0.0.1 knpu_qa.l" | sudo tee -a /etc/hosts

    - sudo /etc/init.d/apache2 restart
script:
    - ./vendor/bin/phpcs --standard=PSR2 src/
    - ./vendor/bin/phpmd src/ text "codesize,design,naming,unusedcode"
    - ./vendor/bin/behat
    - curl http://localhost/
