language: php

php:
    - 5.4

services:
    - mysql

before_script:
    # install behat, mink etc
    # Have to prefer source or hit github rate limit
    - composer install --no-interaction --prefer-source
    # db setup
    - mysql -e 'create database terminaslt;'
    - mysql -utravis terminaslt < fixtures/dump.sql

    - sudo apt-get install apache2 libapache2-mod-fastcgi
    # enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    # configure apache virtual hosts
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart
    - echo "127.0.0.1 terminas.dev" | sudo tee -a /etc/hosts

    #load travis-specific configs
    - mv web/database.config.travis web/database.config.php
    #- mv behat.yml.travis behat.yml

script:
#    - ./vendor/bin/phpcs --standard=PSR2 src/
#    - ./vendor/bin/phpmd src/ text "codesize,design,naming,unusedcode"
    - phpunit
    - ./vendor/bin/behat
    - curl http://127.0.0.1/
    - curl http://terminas.dev/
    - curl http://terminas.dev/term/view/algoritmas/
#    - ps -ef | grep apache
#    - /usr/sbin/apache2 -V | grep SERVER_CONFIG_FILE
#    - cat /etc/apache2/apache2.conf
#    - ls -la /etc/apache2/mods-enabled/
#    - ls -la /etc/apache2/mods-available/
    - cat /etc/apache2/mods-enabled/rewrite.load
    - cat /etc/apache2/mods-enabled/fastcgi.load
    - cat /etc/apache2/mods-enabled/fastcgi.conf
