language: php

php:
    - 5.5
    - 5.4
    - 5.3

services:
    - mysql

before_script:
    # install behat, mink etc
    # Have to prefer source or hit github rate limit
    - composer install --no-interaction --prefer-source
    # db setup
    - mysql -e 'create database terminaslt;'
    - mv web/database.config.travis web/database.config.php

    - sudo apt-get install apache2
    - sudo a2enmod actions
    - sudo a2enmod rewrite
    - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
    - echo "$(curl -fsSL https://gist.github.com/roderik/16d751c979fdeb5a14e3/raw/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
    - echo "$(curl -fsSL https://gist.github.com/roderik/2eb301570ed4a1f4c33d/raw/gistfile1.txt)" | sed -e "s,PATH,`pwd`/web,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
    - sudo service apache2 restart

script:
    - ./vendor/bin/phpcs --standard=PSR2 src/
    - ./vendor/bin/phpmd src/ text "codesize,design,naming,unusedcode"
    - ./vendor/bin/behat
    - curl http://localhost/
